# Generated by Django 3.1.4 on 2021-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.TextField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='keywords',
        ),
    ]
